"Disable compatibility with vi which can cause unexpected issues.
set nocompatible

"Set encoding to utf-8
set encoding=utf-8

"Switch buffers without saving
set hidden

"Enable type file detection. Vim will be able to try to detect the type of file in use.
filetype on

"Enable plugins and load plugin for the detected file type.
filetype plugin on

"Load an indent file for the detected file type.
filetype indent on

filetype detect

"Turn suntax highlighting on.
syntax on

" Add numbers to each line on the left-hand side.
set relativenumber
set number

" Highlight cursor line underneath the cursor horizontally.
set cursorline

" Set tab and shift width to 4 columns.
" Backspace can delete normally in insert mode
set tabstop=4
set shiftwidth=0
set softtabstop=-1
set expandtab

" Do not save backup files.
set nobackup

" Do not let cursor scroll below or above N number of lines when scrolling.
set scrolloff=10

" Do not wrap lines. Allow long lines to extend as far as the line goes.
set nowrap

" While searching though a file incrementally highlight matching characters as you type.
set incsearch

" Ignore capital letters during search.
set ignorecase

" Override the ignorecase option if searching for capital letters.
" This will allow you to search specifically for capital letters.
set smartcase

" Show partial command you type in the last line of the screen.
set showcmd

" Show the mode you are on the last line.
set showmode

" Use highlighting when doing a search.
set hlsearch

" Set the commands to save in history default number is 20.
set history=1000

" Show current row and column
set ruler

" Hide toolbar and scrollbar
set go-=T
set go-=r
set go-=L

" Set font.
set guifont=Consolas:h12

" Default colorscheme.
colorscheme molokai
let g:molokai_original = 1
let g:molokai_italic = 0

let g:use_brackets=1

" Language specifics
if &filetype=='cpp'
    source $LANG/_cpp.vim
endif
if &filetype=='markdown'
    source $LANG/_md.vim
endif

" Mappings
let mapleader = " "
inoremap ii <esc>
nnoremap <silent> <leader><cr> :noh<cr>

" Center screen after ctrl-d
nnoremap <C-d> <C-d>zz
nnoremap <C-u> <C-u>zz

" Brackets
if g:use_brackets==1
    inoremap $1 ()<esc>i
    inoremap $2 []<esc>i
    inoremap $3 {}<esc>i
    inoremap $4 {<esc>o}<esc>O
    inoremap $q ''<esc>i
    inoremap $e ""<esc>i
    inoremap $t <><esc>i

    vnoremap $1 <esc>`>a)<esc>`<i(<esc>
    vnoremap $2 <esc>`>a]<esc>`<i[<esc>
    vnoremap $3 <esc>`>a}<esc>`<i{<esc>
    vnoremap $q <esc>`>a'<esc>`<i'<esc>
    vnoremap $e <esc>`>a"<esc>`<i"<esc>
    vnoremap $t <esc>`>a><esc>`<i<<esc>
endif

" Maximize window
autocmd GUIEnter * simalt ~x

" Set path to current file path
autocmd BufEnter * silent! lcd %:p:h   
autocmd BufWritePost * silent! lcd %:p:h

" Not comment next line
au filetype * set formatoptions-=cro

"Remove LF
set ff=unix

"Add mappings for terminal
map <Leader>t :bo vsp<bar>:term ++curwin ++close<cr><c-w>:vert res 50<cr>
tmap <Leader>t <c-w>:bo vsp <bar> :term ++curwin ++close<cr>

map <Leader>T :tab term ++close<cr>
tmap <Leader>T <c-w>:tab term ++close<cr>

tmap <Leader>p <c-w>"*
